### ISSUE TITLE
Provide a Day2 Ops experience for microservices (define, observe, manage) using kAppNav open source

### ISSUE THREAD

**Issue by barecode** [kabanero-io/roadmap#70]
Include the kAppNav open source project to be installed by Kabanero, and exposed as part of the Kabanero experience within OKD console. The user experience cannot just be a be a "big of bits" but rather integrated with the full Kabanero experience.

Some high-level TODOs which are necessary for this epic to be resolved:
- [x] Include kAppNav to kabanero.io site experience. This requires...
  - [ ] a logo icon on the site
  - [ ] an introduction blog (@barecode)
  - [ ] a how-to guide (@cvignola)
  - [ ] an end-to-end video to demonstrate use of kAppNav within Kabanero
- [x] Include kAppNav to kabanero install operator
- [x] Include kAppNav to kabanero UI experience
- [x] Include pointers from kabanero documentation to kAppNav documentation (GH pages or similar)

**Comment by barecode** [comment]
Related Issues:
https://github.com/kabanero-io/kabanero-operator/issues/116

**Comment by puciral** [comment]
Here is our issue in our Dev-Ex design repo:
https://github.ibm.com/dev-ex/icap-design/issues/92

**Comment by marikaj123** [comment]
@dianak2016 - can a release be assigned to the Epic?

**Comment by mtamboli** [comment]
Would like to get scope of this feature. Would this be installed by default with kabanero? How would this feature help Jane/Todd/Champ - high level use cases?

**Comment by marikaj123** [comment]
@barecode  and @stevekinder-ibm  - who can provide the details required by SVT?

**Comment by cvignola** [comment]
@mtamboli Kabanero 0.2.x optionally installs kAppNav (you have to answer 'y' when asked) while running the install script.  @kaczyns please keep me honest.  

@barecode said he would provide scenarios.   I would say at minimum:

1. install Kabanero, including kAppNav
2. deploy an application
3. open kAppNav UI and see application and its components

@mtamboli I can work with you on step 2 to ensure that step 3 is possible.  I need to know more about how you are creating/deploying your application in order to do so.  Please contact me when you are ready. Thanks

**Comment by mtamboli** [comment]
@cvignola We will be using appsody operator installed with kabanero to deploy application. Will get in touch with you.

**Comment by alohr51** [comment]
@cvignola for your first point about installing kAppNav - that was the original function, but it was changed to not install by default (to avoid reads breaking current automation flows)

You'll have to set env var `ENABLE_KAPPNAV` to `yes` before running the install script to install it. https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/install-kabanero-foundation.sh#L13

**Comment by stephenkinder** [comment]
@cvignola So SVT should be using the Kabanero pipelines.  The pipeline template is here: https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/incubator/deploy-task.yaml ...  you can see it just applies the Appsody app-deploy.yaml.  The Kabanero operator has configured the Appsody operator to watch for CRDs in the targetNameSpace list.

**Comment by barecode** [comment]
Here are the SVT scenarios and general GA release acceptance criteria:
1. kAppNav can be installed as part of the Kabanero install flow (as per Tim's earlier comment, this requires you to set the ENABLE_KAPPNAV=yes environment variable)
2. kAppNav should also be separately installable using the kAppNav operator, following the instructions available from https://kappnav.io/  (please let us know if the installation steps are not sufficiently clear)
3. Once installed, kAppNav's icon should be visible from the OKD cataloge/service console. Given no applications will likely have been installed, no applications should be visible in the kAppNav GUI.
4. Once an application is built and deployed using Kabanero, the application (and its components) should be visible in the kAppNav GUI.
5. The Application visible in kAppNav should allow you to navigate around and inspect and discover the various components which comprise the application.

**Comment by marikaj123** [comment]
SVT team is looking after testing this Epic and cover as many scenarios as they can.

**Comment by barecode** [comment]
Re: inclusion into kabanero.io, the kappnav people have some thoughts on how that might be done:
https://github.com/kappnav/Issues/issues/40

**Comment by marikaj123** [comment]
@cvignola and @barecode - are we going to deliver the child issue 'Introduce KnappNav in kabanero.io' in release v0.2?

**Comment by alohr51** [comment]
@marikaj123 you should make that comment inside the issue you are referring to.

**Comment by barecode** [comment]
This epic remains open until we deliver the Guide on Kabanero.io. I am not sure what the Issue is right now to link it though.

**Comment by alohr51** [comment]
@barecode if the guide is complete then the ID team needs to review it first, then Alan Little & Nate Ziemann need to do a final review to approve it, then it can get linked on kabanero.io

**Comment by marikaj123** [comment]
@jantley-ibm - Can you please help with reviewing the Guide and adding the ID review label, accordingly.

**Comment by marikaj123** [comment]
kAppNav guide for kabanero.io is complete.  Next step is waiting for Nate/Alan signoff and then actual publish.  Richard Walls is handling that review.

**Comment by marikaj123** [comment]
Work will continue in the next release

**Comment by marikaj123** [comment]
@cvignola - Pipeline to use Appsody build to get kAppNav labels generated.

**Comment by marikaj123** [comment]
According to Chris, The guide is published.  The logo, blog, and video are still in the backlog and candidates for 0.4.0

**Comment by marikaj123** [comment]
Needs pipeline to complete the bug fix: https://github.com/kabanero-io/kabanero-pipelines/issues/132

**Comment by marikaj123** [comment]
@cvignola - What is the status of video "Create end-to-end video for kAppNav"

**Comment by cvignola** [comment]
The kAppNav guide is published:  https://kabanero.io/guide/using-kAppNav/

**Comment by marikaj123** [comment]
According to Chris V. the feature wor is complete and can be closed.  The video will be complete during this month and will be tracked seperatly.
